#This config is YAML based and supports plush templating,
# https://github.com/gobuffalo/plush
#
# For support configuration resources, see, 
# https://github.com/bmc-toolbox/bmclib/blob/master/cfgresources/
#
syslog:
  server: ldaps.example.com
  port: 514
  enable: true #defaults to false if not specified

user:
  - name: Administrator
    password: changeme
    role: admin
    enable: true
  - name: foobar
    password: changeme
    role: user
    enable: false

ldap:
  server: ldaps.example.com
  port: 636
  enable: true
  baseDn: ou=People,dc=example,dc=com
  userAttribute: uid
  groupAttribute: memberUid
  searchFilter: objectClass=posixAccount

ldapGroup:
  - role: admin
    group: cn=<%= vendor %>,cn=bmcAdmins
    groupBaseDn: ou=Group,dc=example,dc=com #the baseDn to lookup group in.
    enable: true
  - role: user
    group: cn=<%= vendor%>,cn=bmcUsers #the group in ldap
    groupBaseDn: ou=Group,dc=example,dc=com #the baseDn to lookup group in.
    enable: false
  - role: user
    group: RemoveGroup
    enable: false
# Declares configuration for HTTPS certs
# If any of the params below differ in the current cert,
# a CSR is generated on the BMC and passed to the signer (see bmcbutler.yml)
# the signed cert is then uploaded to the BMC.
httpsCert:
   renewBeforeExpiry: 720h # accepts a time.Duration string
   # by default only the cert expiry period is checked, to check other attributes list them here.
   validateAttributes: 
     - commonName
     - organizationName
     - subjectAltName 
   attributes:
     commonName: <%= serial %>.bmc.example.com #serial as part of CN
     organizationName: Acme B.V.
     organizationUnit: foo
     locality: Amsterdam
     stateName: Noord-Holland
     countryCode: NL
     email: admin@example.com
     subjectAltName: <%= ipaddress %> # IPAddress as SAN.
ntp:
   enable: true
   server1: ntp0.example.com
   server2: ntp1.example.com
   server3: ntp3.example.com
   timezone: CET

network:
  dnsFromDhcp: true  #bmc to get its DNS address from dhcp
  sshEnable: true
  sshPort: 22
  solEnable: true    #serial over lan
  ipmiEnable: true
  ipmiPort: 623
  dhcpEnable: true
  kvmMediaPort: 17988   # KVM Virtual Media Port
  kvmConsolePort: 17990 # KVM console port
  DDNSEnable: false     # dynamic dns


#an example of setting the license key based on vendor.
<%= if ( vendor == "hp" ) { %>
license:
  key: ASDFKLAMDNARALKNBA123
<% } %>

#Bios configuration, declared per vendor, model.
bios:
  dell:
    idrac9bios:
      PxeDev1EnDis: Enabled
      PxeDev2EnDis: Disabled
      PxeDev3EnDis: Disabled
      PxeDev4EnDis: Disabled

#Chassis setup configuration to be declared only if various asset attributes match.
<%= if ( assetType == "chassis" &&
	 extra["company"] == "skynet" &&
         extra["state"] == "needs-setup" &&
         extra["liveAssets"] == "" ) { %>
setupChassis:
  ipmiOverLan: 
    enable: true     #applies to all blades in a chassis
  flexAddress: 
    enable: false    #applies to all blades in a chassis
  dynamicPower: 
    enable: false    #DPSE on M1000e, Dynamic power for the c7000.
   addBladeBmcAdmins: #Add/Mod admin accounts to all blades in the chassis.
    - name: Administrator
      password: foobar123
    - name: barbar
      password: barbar
  removeBladeBmcUsers: #Remove admin accounts from all blades in the chassis.
    - name: olduser
    - name: foo
<% } %>
